FROM python:3.6-jessie

RUN pip install numpy  \
    && pip install scipy  \
    && pip install flopy  \
    && pip install pika  \
    && pip install mystic  \
    && pip install sklearn  \
    && pip install deap
