version: "2.1"

services:
    modflow-optimization:
        build: ./docker-optimization
        restart: always
        environment:
            DATA_FOLDER: /optimization_temp_data
            HOST: sheep.rmq.cloudamqp.com
            PORT: 5672
            VIRTUAL_HOST: ylfqreqi
            USER: ylfqreqi
            PASSWORD: oe3Hqc_nPWomlp2eDnq5Chwtnfy3jnBk
            REQUEST_QUEUE: optimization_request_queue
            RESPONSE_QUEUE: optimization_response_queue
            SIMULATION_REQUEST_QUEUE: simulation_request_queue
            SIMULATION_RESPONSE_QUEUE: simulation_response_queue
        volumes:
            - ../optimization_temp_data:/optimization_temp_data
            - ../../InowasOptimization:/InowasOptimization
            - ./scripts:/app
        command: python /InowasOptimization/OptimizationServer.py

    modflow-optimization-simulation:
        build: ./docker-simulation
        restart: always
        environment:
            DATA_FOLDER: /optimization_temp_data
            HOST: sheep.rmq.cloudamqp.com
            PORT: 5672
            VIRTUAL_HOST: ylfqreqi
            USER: ylfqreqi
            PASSWORD: oe3Hqc_nPWomlp2eDnq5Chwtnfy3jnBk
            REQUEST_QUEUE: simulation_request_queue
            RESPONSE_QUEUE: simulation_response_queue
        volumes:
            - ../optimization_temp_data:/optimization_temp_data
            - ../../InowasOptimization:/InowasOptimization
            - ./scripts:/app
        command: python /InowasOptimization/SimulationServer.py

