FROM tiangolo/uwsgi-nginx-flask:python3.6
RUN pip install flask-restful
RUN pip install flask-cors
RUN pip install numpy==1.12.1
RUN pip install flopy==3.2.6
RUN pip install pika
RUN pip install flask-socketio
