FROM python:3.6-jessie

RUN apt-get update \
    && apt-get install -y netcat

RUN pip install numpy
RUN pip install scipy
RUN pip install flopy
RUN pip install pika
RUN pip install mystic
RUN pip install sklearn
RUN pip install deap
